### ISSUE TITLE
Error reading a .jp2 image

### ISSUE THREAD

**Issue by JPThorne** [MKutuzoff/WaveletCompression#1]
When trying to read the linked [image](https://www.fnordware.com/j2k/relax.jp2) this library gives an `ArgumentException`: 

`System.ArgumentException: 'Value does not fall within the expected range.'` 

at this line: 

```
		private static MarkerType ReadMarkerType(Stream stream) {
			var b = stream.ReadUInt16();
			if (!Enum.IsDefined(typeof(MarkerType), b)) {
				throw new ArgumentException();
			}
			return (MarkerType)b;
		}
```

Is the image incorrect or is there a bug here?

**Comment by MKutuzoff** [comment]
I think it is error in my code.
I don't make reading all markers on standards JP2K. 
I hope in just time I can fixed this issue. I don't recommended this code in production, only for training.

**Comment by JPThorne** [comment]
Thanks for the reply @MKutuzoff will close then. I came across your library while searching GitHub for JPEG2000 converters.
